option('pdf_standard', type: 'combo',
       choices: ['1.7', '2.0', 'a-1b', 'a-1a', 'a-2b', 'a-2u', 'a-2a', 'a-3b', 'a-3u', 'a-3a', 'a-4', 'a-4f', 'a-4e', 'ua-1', 'none'],
       value: 'none',
       description: 'The PDF standard to enforce conformance with')
option('embed_yml', type: 'boolean', value: true, description: 'Embed resume.yml in the PDF and enable clickable links')
option('embed_diploma', type: 'boolean', value: true, description: 'Embed diploma.pdf in the PDF')
option('embed_certs', type: 'boolean', value: false, description: 'Embed certificates in the PDF')
